# To enable Facebook backend; put your token into the FACEBOOK_TOKEN variable, and set FACEBOOK_ENABLE boolean to true.

enable = False
ACCESS_TOKEN = "While_building_a_bot_put_your_bot_token_here__Remember_not_to_share_or_send_this_file_to_github_after_filling_in_the_token"
VERIFY_TOKEN = "While_building_a_bot_put_your_bot_token_here__Remember_not_to_share_or_send_this_file_to_github_after_filling_in_the_token"
